### ISSUE TITLE
Achievements in iOS not showing XP value

### ISSUE THREAD

**Issue by dakikifr** [playgameservices/cpp-ios-basic-samples#2]
Hi,

Using sdk 1.3 or 1.4, if I open the achievements UI (the default one), I'm not seeing the XP associated with the achievements (I have a "0 XP" string instead).
The same code on android works fine and I see the correct XP value.

This is from an alpha version of the game (PlayGames store listing is still in draft mode).
But since it works fine on android, maybe it's not related to being unpublished.

Attached in a screenshot of the iOS version showing 5 unlocked achievements, and 1 locked.
Both the unlocked and the locked show 0 XP.
On android they all correctly show the amount of XP I've set in my listing on google play console (sorry I don't have an android sshot available).

![img_2030](https://cloud.githubusercontent.com/assets/4882169/7123652/fb6e6580-e223-11e4-8582-58c918198015.png)
(Don't worry about the grey rectangles, I've obfuscated the text)

Got the same "bug" from the toasts on iOS (if it helps), showing 0 XP earned.

Thanks

**Comment by dakikifr** [comment]
Hi,

have you managed to produce this bug?
Any idea, news or something?
Do you think it's related to the "not published" state, and so will disappear  once published?
Thanks

**Comment by dakikifr** [comment]
Hi,

could someone please at least reply, either telling me it's not a bug (or is?), or if you cannot produce it on your side?
Thanks

**Comment by claywilkinson** [comment]
@dakikifr  - You confirmed that the Achievements have an XP value in the play console?  I'll build a sample and try to reproduce it.

**Comment by dakikifr** [comment]
Hi,

yes I do confirm, since it's working fine on the Android version (exact same build... except arch of course^^)

**Comment by claywilkinson** [comment]
thanks for confirming the obvious :)  I am building the samples today.

**Comment by dakikifr** [comment]
If you need any more information....
Since I posted this a long time ago, I didn't try with the latest version yet. I'll try today, but I have a much more important issue (that I just posted) using the RealtimeMultiplayer APIs.

**Comment by claywilkinson** [comment]
ok - just to confirm, you are writing c++ for iOS? or is it objective C?

**Comment by dakikifr** [comment]
It's C++ yes (same code for android/iOS).

**Comment by claywilkinson** [comment]
Thanks - We'll take a look

**Comment by dakikifr** [comment]
Great, but I'd rather have critical issue #3 being looked at in priority over this one :)

**Comment by claywilkinson** [comment]
ok :)

**Comment by dakikifr** [comment]
Hi,

Have you got a chance to look at the other issue?
At least to tell me if you managed to reproduce it or if you need more information, or if you don't think it's critical?
Anything :)

**Comment by tyrmullen** [comment]
Confirming that your guess (Apr. 24 post) is precisely the underlying issue here.  It ends up being unrelated to the client SDK-- if you take a look at the HTTP responses, the server returns 0XP for all achievements from a linked app in the "unpublished" state.  So once published, this issue should no longer reproduce.

**Comment by dakikifr** [comment]
Good to know.
I'm closing the issue but I can't validate it's true because I dropped gpg support for my game, since the critical networking issue (#3) I submitted 5 months ago has not been fixed (nor acknowledged even it's easy to reproduce with the informations I provided).
