### ISSUE TITLE
Question about ShowPlayerSelectUI() showing no friend

### ISSUE THREAD

**Issue by kakashidinho** [playgameservices/cpp-ios-basic-samples#7]
Hi,
I'm trying to use ShowPlayerSelectUI() to display player selection list for a real-time multiplayer match, but it displays no friend, despite I have a lot of accounts in my circles.
What I did wrong? The app still in testing phase. I did add 2 accounts to tester list but they are not shown up on the selection list.

Thanks,

**Comment by raygardener** [comment]
I got the same problem with turn-based match. Did you ever find a solution?

**Comment by kakashidinho** [comment]
No, sometimes your friends will appear, sometimes won't. I don't know what is the reason, so I decided to drop Play Game Services and write my own matchmaking system.

**Comment by raygardener** [comment]
Yeah, I may have to do that too. I've contacted Google twice but after a week I haven't heard anything.
